package com.example.demoshop.daoObject;

public class ShopListDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_list.id
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_list.name
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_list.telphone
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    private String telphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_list.id
     *
     * @return the value of shop_list.id
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_list.id
     *
     * @param id the value for shop_list.id
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_list.name
     *
     * @return the value of shop_list.name
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_list.name
     *
     * @param name the value for shop_list.name
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_list.telphone
     *
     * @return the value of shop_list.telphone
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_list.telphone
     *
     * @param telphone the value for shop_list.telphone
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }
}