package com.example.demoshop.daoObject;

public class ShopCommodityDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity.id
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity.name
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity.shop_id
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity.price
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity.id
     *
     * @return the value of shop_commodity.id
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity.id
     *
     * @param id the value for shop_commodity.id
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity.name
     *
     * @return the value of shop_commodity.name
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity.name
     *
     * @param name the value for shop_commodity.name
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity.shop_id
     *
     * @return the value of shop_commodity.shop_id
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity.shop_id
     *
     * @param shopId the value for shop_commodity.shop_id
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity.price
     *
     * @return the value of shop_commodity.price
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity.price
     *
     * @param price the value for shop_commodity.price
     *
     * @mbg.generated Fri Nov 29 16:06:44 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}