package com.example.demoshop.service.model;

public class SckillModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckilled.sckill_id
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    private Integer sckillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckilled.commodity_id
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    private Integer commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckilled.shop_id
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckilled.user_id
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckilled.name
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckilled.price
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckilled.total
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    private Double total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckilled.count
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckilled.sckill_id
     *
     * @return the value of sckilled.sckill_id
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public Integer getSckillId() {
        return sckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckilled.sckill_id
     *
     * @param sckillId the value for sckilled.sckill_id
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public void setSckillId(Integer sckillId) {
        this.sckillId = sckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckilled.commodity_id
     *
     * @return the value of sckilled.commodity_id
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckilled.commodity_id
     *
     * @param commodityId the value for sckilled.commodity_id
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckilled.shop_id
     *
     * @return the value of sckilled.shop_id
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckilled.shop_id
     *
     * @param shopId the value for sckilled.shop_id
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckilled.user_id
     *
     * @return the value of sckilled.user_id
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckilled.user_id
     *
     * @param userId the value for sckilled.user_id
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckilled.name
     *
     * @return the value of sckilled.name
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckilled.name
     *
     * @param name the value for sckilled.name
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckilled.price
     *
     * @return the value of sckilled.price
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckilled.price
     *
     * @param price the value for sckilled.price
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckilled.total
     *
     * @return the value of sckilled.total
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckilled.total
     *
     * @param total the value for sckilled.total
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckilled.count
     *
     * @return the value of sckilled.count
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckilled.count
     *
     * @param count the value for sckilled.count
     *
     * @mbg.generated Tue Dec 10 10:44:56 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}
